# Generated by Django 2.2 on 2020-02-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Blog_title',
            field=models.CharField(max_length=100),
        ),
    ]
