# Generated by Django 2.2 on 2020-02-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200221_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Blog_image',
        ),
    ]
