# Generated by Django 2.2 on 2020-02-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
