# Generated by Django 2.2 on 2020-02-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Blog_image',
        ),
    ]
